/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.notifications;

import java.awt.BorderLayout;
import java.util.List;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.OutlineView;
import systems.tech247.pdr.UtilityPDR;

/**
 *
 * @author Admin
 */
public class NotificationsBirthDayPanel extends javax.swing.JPanel implements ExplorerManager.Provider {

    
    ExplorerManager em = UtilityPDR.emBirthDays;
    /**
     * Creates new form BirthDayPanel
     */
    public NotificationsBirthDayPanel(List list) {
        initComponents();
        OutlineView ov = new OutlineView("Employee Name");
        ov.addPropertyColumn("dept", "Department");
        ov.addPropertyColumn("bday", "Birth Date");
        ov.getOutline().setRootVisible(false);
        setLayout(new BorderLayout());
        add(ov);
        UtilityPDR.loadBirthDays(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
